Fixed issus with Fedora 36
TNO-MPC/protocols.distributed_keygen pull request #2
Opened 2022-08-17 14:21 UTC by rtaiello

I tested with Fedora 36 and localhost is translated in ::: rather than 127.0.0.1. It might be better to change it with 127.0.0.1

2022-08-17 15:06 UTC, ThomasTNO requested changes
Thanks for catching this flaw in the documentation!

Made some suggestions before merging. Apart from those could you also modify line 262 in the README.md file to
```python
pool.add_http_server(server_port)
```
and the typo on line 175 to
```
### Advanced usage
```

Thanks again

2022-08-17 15:06 UTC, ThomasTNO commented on README.md
> +    pool.add_http_server(server_port, "127.0.0.1")
```suggestion
    pool.add_http_server(server_port)
```

2022-08-17 15:06 UTC, ThomasTNO commented on README.md
> +        pool.add_http_client(f"client{client_port}", "127.0.0.1", client_port)
```suggestion
        pool.add_http_client(f"client{client_port}", "localhost", client_port)
```

2022-08-17 17:42 UTC, ThomasTNO commented
> Thanks for catching this flaw in the documentation!
> 
> Made some suggestions before merging. Apart from those could you also modify line 262 in the README.md file to
> 
> ```python
> pool.add_http_server(server_port)
> ```
> 
> and the typo on line 175 to
> 
> ```
> ### Advanced usage
> ```
> 
> Thanks again

@rtaiello if you modify these I'll merge the PR.

2022-08-22 13:24 UTC, rtaiello commented
Thanks @ThomasTNO I think I've done, I just commited them.

Let me know, thanks.

2022-08-22 13:33 UTC, ThomasTNO approved these changes

2022-08-22 13:35 UTC, merged

2022-08-22 13:40 UTC, ThomasTNO commented
Incorporated, thanks a lot for the community contribution @rtaiello!